project_level_two/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social'))
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views
from .views import SearchResultsView


app_name = 'store'

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:product_id>/', views.detail, name='detail'),
    path('store/', views.store, name='store'),
    path('category/<int:category_id>/', views.category, name='category'),
    path('website/<int:website_id>/', views.website, name='website'),
    path('about-us/', views.about_us, name='about_us'),
    path('search-results/', SearchResultsView.as_view(), name='search_results'),
    path('create/', views.image_create, name='create'),
    path('mybookmarks/', views.mybookmarks, name='mybookmarks'),
    path('mybookmark/<int:bookmark_id>/', views.mybookmark, name='mybookmark'),
    path('like/', views.image_like, name='like'),
    path('mobile-search/', views.mobile_search, name='mobile_search')
]

store/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='uploads/', blank=True)

    def __str__(self):
        return self.name


class Website(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    website = models.ForeignKey(Website, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField()
    url = models.URLField()
    image = models.URLField()
    price = models.CharField(max_length=100)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='images_liked', blank=True)

    def __str__(self):
        return self.name


class Image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='images_created', on_delete=models.CASCADE)
    website = models.CharField(max_length=100, default='Website name', blank=True)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    url = models.URLField(max_length=2000)
    image = models.ImageField(upload_to='images/%Y/%m/%d/')
    description = models.TextField(blank=True)
    price = models.CharField(max_length=100, default='$', blank=True)
    created = models.DateField(auto_now_add=True)


    class Meta:
        indexes = [
        models.Index(fields=['-created']),
        ]
        ordering = ['-created']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

store/forms.py
from django.core.files.base import ContentFile
from django.utils.text import slugify
import requests
from django import forms
from .models import Image


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['website','title', 'url', 'description', 'price']
        widgets = {
        'url': forms.HiddenInput,
        }

    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpg', 'jpeg', 'png']
        extension = url.rsplit('.', 1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError('The given URL does not match valid image extensions.')
        return url

    def save(self, force_insert=False,
             force_update=False,
             commit=True):
        image = super().save(commit=False)
        image_url = self.cleaned_data['url']
        name = slugify(image.title)
        extension = image_url.rsplit('.', 1)[1].lower()
        image_name = f'{name}.{extension}'
        # download image from the given URL
        response = requests.get(image_url)
        image.image.save(image_name,  ContentFile(response.content),
                         save=False)
        if commit:
            image.save()
        return image

store/views.py
from django.shortcuts import render, redirect
from .models import Product, Category, Website
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import TemplateView, ListView
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import ImageCreateForm
from .models import Image
from django.http import JsonResponse
from django.views.decorators.http import require_POST
# from .adding import process
#
# process()


def index(request):
    categories = Category.objects.all()
    category_list = Category.objects.order_by('-id')
    product_list = Product.objects.order_by('-id')
    paginator = Paginator(product_list, 12)
    paginator2 = Paginator(product_list, 6)
    category_paginator = Paginator(category_list, 2)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
        products2 = paginator2.page(page)
        categories2 = category_paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        products = paginator.page(1)
        products2 = paginator2.page(1)
        categories2 = category_paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        products = paginator.page(paginator.num_pages)
        products2 = paginator2.page(paginator2.num_pages)
        categories2 = category_paginator.page(category_paginator.num_pages)
    context = {'categories': categories,
               'products': products,
               'products2': products2,
               'categories2': categories2}
    return render(request, 'store/index.html', context)


def category(request, category_id):
    category = Category.objects.get(id=category_id)
    product_list = category.products.order_by('-id')
    paginator = Paginator(product_list, 20)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        products = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        products = paginator.page(paginator.num_pages)

    context = {'category': category,
               'products': products,
               }
    return render(request, 'store/category.html', context)


def website(request, website_id):
    website = Website.objects.get(id=website_id)
    categories = Category.objects.all()
    product_list = website.products.order_by('-id')
    product_list_random = website.products.order_by('?')
    product_list_random2 = website.products.order_by('?')
    paginator = Paginator(product_list, 3)
    paginator_random = Paginator(product_list_random, 3)
    paginator_random2 = Paginator(product_list_random2, 3)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
        products_random = paginator_random.page(page)
        products_random2 = paginator_random2.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        products = paginator.page(1)
        products_random = paginator_random.page(1)
        products_random2 = paginator_random2.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        products = paginator.page(paginator.num_pages)
        products_random = paginator_random.page(paginator.num_pages)
        products_random2 = paginator_random2.page(paginator.num_pages)

    context = {'category': category,
               'products': products,
               'categories': categories,
               'products_random': products_random,
               'products_random2': products_random2,
               'website': website,
               }
    return render(request, 'store/website.html', context)


def about_us(request):
    categories = Category.objects.all()
    context = {'categories': categories}
    return render(request, 'store/about_us.html', context)


class SearchResultsView(ListView):
    model = Product
    template_name = 'store/search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Product.objects.filter(
        Q(name__icontains=query) | Q(category__name__icontains=query) | Q(website__name__icontains=query) | Q(price__icontains=query)
        )
        return object_list


def detail(request, product_id):
    product = Product.objects.get(id=product_id)
    product_list = Product.objects.filter(category=product.category)
    paginator = Paginator(product_list, 6)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        products = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        products = paginator.page(paginator.num_pages)
    context = {'product': product, 'products': products}
    return render(request, 'store/detail.html', context)


def store(request):
    product_list = Product.objects.order_by('-id')
    paginator = Paginator(product_list, 12)  # 12 categories in each page
    page = request.GET.get('page')
    try:

        products = paginator.page(page)
    except PageNotAnInteger:

        products = paginator.page(1)
    except EmptyPage:

        products = paginator.page(paginator.num_pages)

    categories = Category.objects.all()

    context = {'products': products, 'categories': categories}
    return render(request, 'store/store.html', context)


@login_required
def image_create(request):
    if request.method == 'POST':
        # form is sent
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            # form data is valid
            cd = form.cleaned_data
            new_image = form.save(commit=False)
            # assign current user to the item
            new_image.user = request.user
            new_image.save()
            messages.success(request, 'Image added successfully')
            # redirect to new created item detail view
            return redirect('store:mybookmarks')
    else:
    # build form with data provided by the bookmarklet via GET
        form = ImageCreateForm(data=request.GET)
    return render(request, 'images/image/create.html', {'section': 'images', 'form': form})


@login_required()
def mybookmarks(request):
    images = Image.objects.filter(user=request.user)
    products = Product.objects.filter(users_like=request.user)
    context = {'images': images, 'products': products}
    return render(request, 'images/image/mybookmarks.html', context)


@login_required()
def mybookmark(request, bookmark_id):
    image = Image.objects.get(id=bookmark_id)
    context = {'image': image}
    return render(request, 'images/image/mybookmark.html', context)


@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    if image_id and action:
        try:
            image = Product.objects.get(id=image_id)
            if action == 'bookmark':
                image.users_like.add(request.user)
            else:
                image.users_like.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except Image.DoesNotExist:
            pass
    return JsonResponse({'status': 'error'})


def mobile_search(request):
    return render(request, 'store/mobile_search.html')

store/templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static '/style.css' %}">
    <link rel="stylesheet" href="{% static '/base.css' %}">
    <link rel="stylesheet" href="{% static '/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static '/css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static '/font-6/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static '/font-6/css/fontawesome.min.css' %}">


    <script
    src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
</head>
<body>
<header class="H1">
        <image class="logo" src="{% static '/images/huey3.jpg' %}"></image>
        <form action="{% url 'store:search_results' %}" method="get">
            <div class="search-nav-bar">
                <input name="q" type="text" placeholder="Search...">
                <!-- <a href=""><i class="fas fa-search"></i></a> -->
            </div>
        </form>

        <div class="user-location">
            <i class="fa-solid fa-location-dot"></i>
            <div class="location-stores">
                <h5>Midlands State University</h5>
                <h5>Gweru, Zimbabwe</h5>
            </div>
        </div>

        <div class="nav-tab">
            <div class="sml-search">
                <a href="{% url 'store:mobile_search' %}"><i class="fas fa-search"></i></a>
            </div>
        {% if request.user.is_authenticated %}
            <div class="user">
                <a href="#" class="btn">{{ request.user.username }}</a>
            </div>
        {% else %}
            <div class="user">
                <a href="{% url 'login' %}" class="btn">Sign In</a>
            </div>
        {% endif %}
        </div>

        <div class="sml-nav">
            <div class="sml-search">
                <a href="{% url 'store:mobile_search' %}"><i class="fas fa-search"></i></a>
            </div>

            <div class="sml-nav-2">

                <button class="mobile-toggle"
                aria-controls="pry-nav" aria-expanded="false">
                <span class="sr-only">Menu</span>
            </button>

            <nav>
                <ul id="pry-nav" data-visible="false" class="pry-nav">
                    <div class="profile-acc">
                        <img src="{% static '/images/huey2.jpg' %}" alt="">
                          {% if request.user.is_authenticated %}
                            <div class="profile-acc-details">
                                <h2><span><i class="fas fa-user"></i></span>{{ request.user.username }}</h2>
                                <a href="{% url 'logout' %}">Log Out</a>
                            </div>
                        {% else %}
                            <div class="profile-acc-details">
                                <h2><span><i class="fas fa-user"></i></span>Sign In/Up</h2>
                                <a href="{% url 'login' %}">Log In</a>
                            </div>
                        {% endif %}
                    </div>
                    <li><a href="{% url 'store:index' %}"><span><i class="fas fa-home"></i></span> Home</a></li>
                    <li><a href="{% url 'store:store' %}"><span> <i class="fas fa-store"></i></span> Store</a></li>
                    <li><a href="{% url 'store:mybookmarks' %}"><span><i class="fas fa-bookmark"></i></span> Bookmarks</a></li>

                    <li><a href="#"><span><i class="fas fa-phone"></i></span> Contact Us</a></li>

                    <div class="user-location user-location-beta">
                        <i class="fa-solid fa-location-dot"></i>
                        <div class="location-stores">
                            <h5>Midlands State University</h5>
                            <h5>Gweru, Zimbabwe</h5>
                        </div>
                    </div>
                </ul>
            </nav>
            </div>
        </div>

    </header>

    <header class="H2">
        <nav class="nav-bar">
            <ul>
                <li><a href="{% url 'store:index' %}">Home</a></li>
                <li><a href="{% url 'store:store' %}">Store</a></li>
                <li><a href="{% url 'store:mybookmarks' %}">My Bookmarks</a></li>
                <li><a href="#">Contact Us</a></li>
            </ul>
        </nav>
    </header>
     {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">
                    {{ message|safe }}
                    <a href="#" class="close">x</a>
                </li>
            {% endfor %}
        </ul>
     {% endif %}
{% block content %}
{% endblock content %}
     <footer class="featured foot-det">
        <div class="col">
            <h1>Pricey!!</h1>

            <div class="follow">
                <h3>Follow Us</h3>
                <div class="vendor-tag">
                    <i style="color: white;" class="fab fa-facebook-f"></i>
                    <i style="color: white;" class="fab fa-instagram"></i>
                </div>
            </div>
        </div>

        <div class="col">
            <h3>About</h3>
            <a href="#">About Us</a>
            <a href="#">Terms & Conditions</a>
            <a href="#">Privacy Policy</a>
        </div>

        <div class="col">
            <h3>My Account</h3>
            {% if request.user.is_authenticated %}
                <a href="{% url 'logout' %}">Sign Out</a>
            {% else %}
                <a href="{% url 'login' %}">Sign In</a>
            {% endif %}
            <a href="#">Contact Us</a>
        </div>

        <section class="line">
            <p>Copyright 2023 @Pricey. All rights reserved.</p>
        </section>

    </footer>


    <script src="{% static '/main2.js' %}" defer></script>
    <script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
    <script type="text/javascript">
        $('.main-carousel').flickity({
            cellAlign: 'left',
            wrapAround:true,
            freeScroll: true
        });
    </script>
    <script src="//cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>

    <script>
         const csrftoken = Cookies.get('csrftoken');
         document.addEventListener('DOMContentLoaded', (event) => {
         // DOM loaded
             {% block domready %}
             {% endblock %}
         })
    </script>
</body>
</html>

store/templates/store/category.html
{% extends 'store/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}{{ category.name }}{% endblock title %}
</head>
<body>
    {% block content %}
        <section style="background-image:linear-gradient(rgba(0, 0, 0, 0.527),rgba(0, 0, 0, 0.5)), url({{ category.image.url }});" class="top-container">
            <div class="top-container-info">
                <h5>{{ category.name }}.</h5>
                <h1>Store Gallery</h1>
                <p>Check out our latest {{ category.name }}<br>at accessible prices.</p>
            </div>
        </section>

        <section class="product-items">
            {% for product in products %}
                <div class="product">
                    <div class="product-content">
                        <div class="product-img">
                            <img src="{{ product.image }}" alt="" onclick="window.location.href='{% url 'store:detail' product.id %}';">
                        </div>

                        <div class="product-info">
                            <div class="product-info-top" onclick="window.location.href='{% url 'store:category' product.category.id %}';">
                                <h5>{{ product.category }}</h5>
                            </div>

                            <div class="product-info-bottom" onclick="window.location.href='{% url 'store:detail' product.id %}';">
                                <h2 class="name">{{ product.name|truncatechars:25 }}</h2>
                                <h2 class="price">{{ product.price }}</h2>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}

        </section>
        {% include "store/pagination.html" with page=products %}
    {% endblock content %}
    
</body>
</html>

store/templates/store/detail.html
{% extends 'store/base.html' %}
{% load static %}

{% block title %}{{product.name }}{% endblock title %}


{% block content %}
    <section id="prodetails" class="featured">
        <div class= "singleimg">
            <a href="{{ product.url }}"><img class="big-img" src="{{ product.image }}" width="100%" id="Mainimg" alt=""></a>
        </div>

        <div class="single-pro-details">
            <h5>{{ product.website }}</h5>

            <h3>{{ product.name }}</h3>

            <h4 class="price">{{ product.price }}</h4>

            <h4 class="prodet">Details</h4>
            <p>{{ product.description }}</p>

            <h4 style="margin-top: 3%;">Like what you see?</h4>
            <div class="vendor-details">
                {% if request.user.is_authenticated %}
                    {% with total_likes=product.users_like.count users_like=product.users_like.all %}
                         <div class="image-info">
                            <div>

                                <a href="#" data-id="{{ product.id }}" data-action="{% if request.user in users_like %}bookmarked {% else %}bookmark{% endif %}" class="like button">
                                    {% if request.user not in users_like %}
                                        Bookmark
                                    {% else %}
                                        Bookmarked
                                    {% endif %}
                                </a>
                            </div>
                         </div>
                    {% endwith %}
                {% else %}
                    <div class="vendor-img">
                        <a href="{% url 'login' %}"><h2>Login to Bookmark...</h2></a>
                    </div>
                {% endif %}


            </div>
        </div>

    </section>

    <div class="topic">
        <h1>Related Items</h1>
    </div>

    <section class="product-items">
        {% for product in products %}
            <div class="product">
                <div class="product-content">
                    <div class="product-img">
                        <img src="{{ product.image }}" alt="" onclick="window.location.href='{% url 'store:detail' product.id %}';">
                    </div>

                    <div class="product-info">
                        <div class="product-info-top" onclick="window.location.href='{% url 'store:category' product.category.id %}';">
                            <h5>{{ product.category }}</h5>
                        </div>

                        <div class="product-info-bottom" onclick="window.location.href='{% url 'store:detail' product.id %}';">
                            <h2 class="name">{{ product.name }}</h2>
                            <h2 class="price">{{ product.price }}</h2>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}

    </section>
{% endblock content %}


    

{% block domready %}
      const url = '{% url "store:like" %}';
      var options = {
        method: 'POST',
        headers: {'X-CSRFToken': csrftoken},
        mode: 'same-origin'
      }


      document.querySelector('a.like')
              .addEventListener('click', function(e){
        e.preventDefault();
        var likeButton = this;

        // add request body
        var formData = new FormData();
        formData.append('id', likeButton.dataset.id);
        formData.append('action', likeButton.dataset.action);
        options['body'] = formData;

        console.log(csrftoken);
        // send HTTP request
        fetch(url, options)
        .then(response => response.json())
        .then(data => {
          if (data['status'] === 'ok')
          {

            var previousAction = likeButton.dataset.action;

            // toggle button text and data-action
            var action = previousAction === 'bookmark' ? 'bookmarked' : 'bookmark';
            likeButton.dataset.action = action;
            likeButton.innerHTML = action;

            // update like count
            console.log('Updating like count...');
            var likeCount = document.querySelector('span.count .total');
            var totalLikes = parseInt(likeCount.innerHTML);
            likeCount.innerHTML = previousAction === 'like' ? totalLikes + 1 : totalLikes - 1;
          } else {
                console.log(data);
            }

        })
      });
{% endblock %}

store/templates/store/index.html
{% extends 'store/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    {% block title %}Home{% endblock title %}

</head>

<body>
    {% block content %}
        <section class="top-container">
            <div class="top-container-info">
                <h1>PRICEY!!</h1>
                <p>We offer a wide range of electronic products<br>at accessible prices.</p>
                <a href="{% url 'store:store' %}" class="btn">Shop Now</a>
            </div>

        </section>

        <section class="top">
            {% for category in categories %}

                <div style="background-image:linear-gradient(rgba(0, 0, 0, 0.527),rgba(0, 0, 0, 0.5)), url({{category.image.url}});" class="top-banter">
                    <h4>{{ category.name }}</h4>
                    <p>{{ category.description }}</p>
                    <a href="{% url 'store:category' category.id %}" class="btn-cat">Shop Now</a>
                </div>

            {% endfor %}


        </section>

        <div class="topic">
            <h5>Hot Items</h5>
            <h1>New Arrivals</h1>
        </div>

        <section class="product-items">
            {% for product in products %}
                <div class="product">
                    <div class="product-content">
                        <div class="product-img">
                            <img src="{{ product.image }}" alt="" onclick="window.location.href='{% url 'store:detail' product.id %}';">
{#                            {{ product.url }}#}
                        </div>

                        <div class="product-info">
                            <div class="product-info-top">
                                <h5>{{ product.category }}</h5>
                            </div>

                            <div class="product-info-bottom">
                                <h2 class="name">{{ product.name|truncatechars:25 }}</h2>
                                <h2 class="price">{{ product.price }}</h2>
                            </div>
                        </div>
                    </div>
                </div>

            {% endfor %}

        </section>

        <section class="banner">

            <div class="banner-info">
                <h1>Introducing Bookmarking</h1>
                <p>Save multiple products on the go...</p>
                <a href="{% url 'store:mybookmarks' %}" class="btn">Bookmark Now</a>
            </div>

        </section>



        <section class="top">
            {% for category in categories2 %}
                <div style="background-image:linear-gradient(rgba(0, 0, 0, 0.527),rgba(0, 0, 0, 0.5)), url({{category.image.url}});" class="top-banter">
                    <h4>{{ category.name }}</h4>
                    <p>{{ category.description }}</p>
                    <a href="{% url 'store:category' category.id %}" class="btn-cat">Shop Now</a>
                </div>
            {% endfor %}



        </section>

        <div class="topic">
            <h5>This Week</h5>
            <h1>Trending</h1>
        </div>

        <section class="trending-items">
            <div class="hot-item">
{#                <h4>All the latest gadgets</h4>#}
{#                <h2>At an affordable price!!</h2>#}
            </div>

            <div class="other-items other-items-alpha">
                <div class="product-items beta">
                    {% for product in products2 %}
                        <div class="product">
                            <div class="product-content">
                                <div class="product-img">
                                    <img src="{{ product.image }}" alt="" onclick="window.location.href='{% url 'store:detail' product.id %}';">
                                </div>

                                <div class="product-info">
                                    <div class="product-info-top" onclick="window.location.href='{% url 'store:category' product.category.id %}';">
                                        <h5>{{ product.category }}</h5>
                                    </div>

                                    <div class="product-info-bottom" onclick="window.location.href='{% url 'store:detail' product.id %}';">
                                        <h2 class="name">{{ product.name|truncatechars:20 }}</h2>
                                        <h2 class="price">{{ product.price }}</h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
            </div>
            </div>
        </section>
    {% endblock content %}
</body>


</html>

store/templates/store/mobile_search.html
{% extends 'store/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% block title %}Search{% endblock title %}
</head>
<body>
    {% block content %}
    <section class="log-in-form"> 
        <div class="sign-up sign-up-beta">
            <header>
                <h1>Search Here</h1>
                <p>Enter a keyword to search for the product that you want from our catalogue.</p>
            </header>
    
            <div class="form-outer">
                <form action="{% url 'store:search_results' %}" method="get">
                    <div class="sign-page slidepage">
      
                    <div class="input-field">
                        <input name="q" type="text" placeholder="Enter Keyword">
                    </div>
                 </div> 
                </form>
            </div>
        </div>
       </section>
    {% endblock content %}
</body>
</html>