project_level_two/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social'))
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views
from .views import SearchResultsView


app_name = 'store'

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:product_id>/', views.detail, name='detail'),
    path('store/', views.store, name='store'),
    path('category/<int:category_id>/', views.category, name='category'),
    path('website/<int:website_id>/', views.website, name='website'),
    path('about-us/', views.about_us, name='about_us'),
    path('search-results/', SearchResultsView.as_view(), name='search_results'),
    path('create/', views.image_create, name='create'),
    path('mybookmarks/', views.mybookmarks, name='mybookmarks'),
    path('mybookmark/<int:bookmark_id>/', views.mybookmark, name='mybookmark'),
    path('like/', views.image_like, name='like'),
    path('mobile-search/', views.mobile_search, name='mobile_search')
]

store/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='uploads/', blank=True)

    def __str__(self):
        return self.name


class Website(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    website = models.ForeignKey(Website, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField()
    url = models.URLField()
    image = models.URLField()
    price = models.CharField(max_length=100)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='images_liked', blank=True)

    def __str__(self):
        return self.name


class Image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='images_created', on_delete=models.CASCADE)
    website = models.CharField(max_length=100, default='Website name', blank=True)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    url = models.URLField(max_length=2000)
    image = models.ImageField(upload_to='images/%Y/%m/%d/')
    description = models.TextField(blank=True)
    price = models.CharField(max_length=100, default='$', blank=True)
    created = models.DateField(auto_now_add=True)


    class Meta:
        indexes = [
        models.Index(fields=['-created']),
        ]
        ordering = ['-created']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

store/forms.py
from django.core.files.base import ContentFile
from django.utils.text import slugify
import requests
from django import forms
from .models import Image


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['website','title', 'url', 'description', 'price']
        widgets = {
        'url': forms.HiddenInput,
        }

    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpg', 'jpeg', 'png']
        extension = url.rsplit('.', 1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError('The given URL does not match valid image extensions.')
        return url

    def save(self, force_insert=False,
             force_update=False,
             commit=True):
        image = super().save(commit=False)
        image_url = self.cleaned_data['url']
        name = slugify(image.title)
        extension = image_url.rsplit('.', 1)[1].lower()
        image_name = f'{name}.{extension}'
        # download image from the given URL
        response = requests.get(image_url)
        image.image.save(image_name,  ContentFile(response.content),
                         save=False)
        if commit:
            image.save()
        return image

store/views.py
from django.shortcuts import render, redirect
from .models import Product, Category, Website
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import TemplateView, ListView
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import ImageCreateForm
from .models import Image
from django.http import JsonResponse
from django.views.decorators.http import require_POST
# from .adding import process
#
# process()


def index(request):
    categories = Category.objects.all()
    category_list = Category.objects.order_by('-id')
    product_list = Product.objects.order_by('-id')
    paginator = Paginator(product_list, 12)
    paginator2 = Paginator(product_list, 6)
    category_paginator = Paginator(category_list, 2)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
        products2 = paginator2.page(page)
        categories2 = category_paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        products = paginator.page(1)
        products2 = paginator2.page(1)
        categories2 = category_paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        products = paginator.page(paginator.num_pages)
        products2 = paginator2.page(paginator2.num_pages)
        categories2 = category_paginator.page(category_paginator.num_pages)
    context = {'categories': categories,
               'products': products,
               'products2': products2,
               'categories2': categories2}
    return render(request, 'store/index.html', context)


def category(request, category_id):
    category = Category.objects.get(id=category_id)
    product_list = category.products.order_by('-id')
    paginator = Paginator(product_list, 20)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        products = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        products = paginator.page(paginator.num_pages)

    context = {'category': category,
               'products': products,
               }
    return render(request, 'store/category.html', context)


def website(request, website_id):
    website = Website.objects.get(id=website_id)
    categories = Category.objects.all()
    product_list = website.products.order_by('-id')
    product_list_random = website.products.order_by('?')
    product_list_random2 = website.products.order_by('?')
    paginator = Paginator(product_list, 3)
    paginator_random = Paginator(product_list_random, 3)
    paginator_random2 = Paginator(product_list_random2, 3)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
        products_random = paginator_random.page(page)
        products_random2 = paginator_random2.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        products = paginator.page(1)
        products_random = paginator_random.page(1)
        products_random2 = paginator_random2.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        products = paginator.page(paginator.num_pages)
        products_random = paginator_random.page(paginator.num_pages)
        products_random2 = paginator_random2.page(paginator.num_pages)

    context = {'category': category,
               'products': products,
               'categories': categories,
               'products_random': products_random,
               'products_random2': products_random2,
               'website': website,
               }
    return render(request, 'store/website.html', context)


def about_us(request):
    categories = Category.objects.all()
    context = {'categories': categories}
    return render(request, 'store/about_us.html', context)


class SearchResultsView(ListView):
    model = Product
    template_name = 'store/search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Product.objects.filter(
        Q(name__icontains=query) | Q(category__name__icontains=query) | Q(website__name__icontains=query) | Q(price__icontains=query)
        )
        return object_list


def detail(request, product_id):
    product = Product.objects.get(id=product_id)
    product_list = Product.objects.filter(category=product.category)
    paginator = Paginator(product_list, 6)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        products = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        products = paginator.page(paginator.num_pages)
    context = {'product': product, 'products': products}
    return render(request, 'store/detail.html', context)


def store(request):
    product_list = Product.objects.order_by('-id')
    paginator = Paginator(product_list, 12)  # 12 categories in each page
    page = request.GET.get('page')
    try:

        products = paginator.page(page)
    except PageNotAnInteger:

        products = paginator.page(1)
    except EmptyPage:

        products = paginator.page(paginator.num_pages)

    categories = Category.objects.all()

    context = {'products': products, 'categories': categories}
    return render(request, 'store/store.html', context)


@login_required
def image_create(request):
    if request.method == 'POST':
        # form is sent
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            # form data is valid
            cd = form.cleaned_data
            new_image = form.save(commit=False)
            # assign current user to the item
            new_image.user = request.user
            new_image.save()
            messages.success(request, 'Image added successfully')
            # redirect to new created item detail view
            return redirect('store:mybookmarks')
    else:
    # build form with data provided by the bookmarklet via GET
        form = ImageCreateForm(data=request.GET)
    return render(request, 'images/image/create.html', {'section': 'images', 'form': form})


@login_required()
def mybookmarks(request):
    images = Image.objects.filter(user=request.user)
    products = Product.objects.filter(users_like=request.user)
    context = {'images': images, 'products': products}
    return render(request, 'images/image/mybookmarks.html', context)


@login_required()
def mybookmark(request, bookmark_id):
    image = Image.objects.get(id=bookmark_id)
    context = {'image': image}
    return render(request, 'images/image/mybookmark.html', context)


@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    if image_id and action:
        try:
            image = Product.objects.get(id=image_id)
            if action == 'bookmark':
                image.users_like.add(request.user)
            else:
                image.users_like.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except Image.DoesNotExist:
            pass
    return JsonResponse({'status': 'error'})


def mobile_search(request):
    return render(request, 'store/mobile_search.html')

store/templates/images/image/create.html
{% extends "store/base.html" %}
{% block title %}Bookmark an image{% endblock %}
{% block content %}


    <section class="log-in-form">

        <div class="sign-up">
            <header><h1>Bookmark</h1></header>


            <div class="form-outer">
                <form method="post">
                    <div class="sign-page slidepage">


                    {{ form.as_p }}
                    {% csrf_token %}

                    <img src="{{ request.GET.url }}" class="image-preview">
                    <div class="input-field nextBtn">
                        <button style="font-size: 1.1rem; font-weight:600; letter-spacing:1px;" class="btn">Bookmark it</button>
                    </div>
                 </div>

                </form>
            </div>
        </div>
    </section>
{% endblock %}

store/templates/images/image/mybookmark.html
{% extends 'store/base.html' %}
{% load static %}

{% block title %}{{ image.title }}{% endblock title %}


{% block content %}
    <section id="prodetails" class="featured">
        <div class= "singleimg">
            <a href="{{ image.url }}"><img class="big-img" src="{{ image.image.url }}" width="100%" id="Mainimg" alt=""></a>
        </div>

        <div class="single-pro-details">
            <h5>{{ image.website }}</h5>

            <h3 >{{ image.title }}</h3>

            <h4 class="price">{{ image.price }}</h4>

            <h4 class="prodet">Details</h4>
            <p>{{ image.description }}</p>



        </div>

    </section>



{% endblock content %}

store/templates/images/image/mybookmarks.html
{% extends "store/base.html" %}
{% load static %}
{% block title %}My Bookmarks{% endblock %}

{% block content %}
    <section style="background-image:linear-gradient(rgba(0, 0, 0, 0.527),rgba(0, 0, 0, 0.5)), url({% static '/images/markus-spiske-BTKF6G-O8fU-unsplash.jpg' %});" class="top-container">
        <div class="top-container-info">
            <h5>{{ request.user.username }}.</h5>
            <h1>My Bookmarks</h1>
{#            {% with total_images_created=request.user.images_created.count %}#}
{#                <p>You have bookmarked {{ total_images_created }} image{{ total_images_created|pluralize }}</p>#}
{#            {% endwith %}#}
             <p>To bookmark products from this website, click on a specific product and press Bookmark it.</p>
            <p>Drag the following button to your bookmarks toolbar to bookmark products from other websites → <a href="javascript:{% include "bookmarklet_launcher.js" %}" >Bookmark it</a></p>
        </div>
    </section>
    <section class="product-items">
        {% for product in products %}
            <div class="product">
                <div class="product-content">
                    <div class="product-img">
                        <img src="{{ product.image }}" alt="" onclick="window.location.href='{% url 'store:detail' product.id %}';">
                    </div>

                    <div class="product-info">
                        <div class="product-info-top" onclick="window.location.href='{% url 'store:detail' product.id %}';">
                            <h5>{{ product.category }}</h5>
                        </div>

                        <div class="product-info-bottom" onclick="window.location.href='{% url 'store:detail' product.id %}';">
                            <h2 class="name">{{ product.name|truncatechars:25 }}</h2>
                            <h2 class="price">{{ product.price }}</h2>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}

    </section>

    <section class="product-items">
        {% for product in images %}
            <div class="product">
                <div class="product-content">
                    <div class="product-img">
                        <img src="{{ product.image.url }}" alt="" onclick="window.location.href='{% url 'store:mybookmark' product.id %}';">
                    </div>

                    <div class="product-info">
                        <div class="product-info-top" onclick="window.location.href='{% url 'store:mybookmark' product.id %}';">
                            <h5>{{ product.website }}</h5>
                        </div>

                        <div class="product-info-bottom" onclick="window.location.href='{% url 'store:mybookmark' product.id %}';">
                            <h2 class="name">{{ product.title|truncatechars:25 }}</h2>
                            <h2 class="price">{{ product.price }}</h2>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}

    </section>


{#    {% include "store/pagination.html" with page=products %}#}
{% endblock content %}